name: SuperC4_ui
description: A sample Polymer application
dependencies:
    browser:
    polymer:
    core_elements:
    paper_elements:
    css_animation:
transformers:
- polymer:
    entry_points: web/superc4_ui.html
